#/geometry/navigator/reset
#/geometry/navigator/verbose 4
#/geometry/navigator/check_mode true
#/geometry/test

/vis/scene/create

#/vis/open ATree
#/vis/ASCIITree/verbose 2

/vis/open DAWNFILE

/vis/scene/add/trajectories
/vis/sceneHandler/attach
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
/vis/scene/endOfEventAction accumulate

#/vis/viewer/reset
#/vis/viewer/flush

/run/beamOn 1

/vis/drawVolume
/vis/viewer/update
/vis/viewer/flush
